services:
  # backend-api:
  #   build:
  #     context: .
  #     dockerfile: api/Dockerfile
  #   expose:
  #     - "8000"
  #   environment:
  #     - DATABASE_URL=${DATABASE_URL}
  #     - SUPABASE_URL=${SUPABASE_URL}
  #     - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
  #   restart: unless-stopped

  discord-bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - CHANNEL_IDS=${CHANNEL_IDS}
    restart: unless-stopped

  frontend-web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        SUPA_URL: ${SUPABASE_URL}
        SUPA_ANON: ${SUPABASE_ANON_KEY}
#       API_URL: ${VITE_API_URL}
    expose:
      - "5175"
    restart: unless-stopped
    # depends_on:
    #   - backend-api
